@echo off
copy "TPL.gba" "TPL_translation.gba"
:: Execute Atlas
Atlas "TPL_translation.gba" tpl_script_000.txt
Atlas "TPL_translation.gba" tpl_script_001.txt
Atlas "TPL_translation.gba" tpl_script_002.txt
Atlas "TPL_translation.gba" tpl_script_003.txt
Atlas "TPL_translation.gba" tpl_script_004.txt
Atlas "TPL_translation.gba" tpl_script_005.txt
Atlas "TPL_translation.gba" tpl_script_006.txt
Atlas "TPL_translation.gba" tpl_script_007.txt
Atlas "TPL_translation.gba" tpl_script_008.txt
Atlas "TPL_translation.gba" tpl_script_009.txt
Atlas "TPL_translation.gba" tpl_script_010.txt
Atlas "TPL_translation.gba" tpl_script_011.txt
Atlas "TPL_translation.gba" tpl_script_012.txt
Atlas "TPL_translation.gba" tpl_script_013.txt
Atlas "TPL_translation.gba" tpl_script_014.txt
Atlas "TPL_translation.gba" tpl_script_015.txt
Atlas "TPL_translation.gba" tpl_script_016.txt
Atlas "TPL_translation.gba" tpl_script_017.txt
Atlas "TPL_translation.gba" tpl_script_018.txt
Atlas "TPL_translation.gba" tpl_script_019.txt
Atlas "TPL_translation.gba" tpl_script_020.txt
Atlas "TPL_translation.gba" tpl_script_021.txt
Atlas "TPL_translation.gba" tpl_script_022.txt
Atlas "TPL_translation.gba" tpl_script_023.txt
Atlas "TPL_translation.gba" tpl_script_024.txt
Atlas "TPL_translation.gba" tpl_script_025.txt
Atlas "TPL_translation.gba" tpl_script_026.txt
Atlas "TPL_translation.gba" tpl_script_027.txt
Atlas "TPL_translation.gba" tpl_script_028.txt
Atlas "TPL_translation.gba" tpl_script_029.txt
Atlas "TPL_translation.gba" tpl_script_030.txt
Atlas "TPL_translation.gba" tpl_script_031.txt
Atlas "TPL_translation.gba" tpl_script_032.txt
Atlas "TPL_translation.gba" tpl_script_033.txt
Atlas "TPL_translation.gba" tpl_script_034.txt
Atlas "TPL_translation.gba" tpl_script_035.txt
Atlas "TPL_translation.gba" tpl_script_036.txt
Atlas "TPL_translation.gba" tpl_script_037.txt
Atlas "TPL_translation.gba" tpl_script_038.txt
Atlas "TPL_translation.gba" tpl_script_039.txt
pause